### ISSUE TITLE
multiple npm ERR

### ISSUE THREAD

**Issue by idan666** [Azure-Samples/meanjs#1]
Hi, I worked my way up this guide on mac:
https://docs.microsoft.com/en-us/azure/app-service-web/app-service-web-tutorial-nodejs-mongodb-app
with the following configurations:
node: 6.9.1
npm : 3.10.8
mongoDB: 3.0.7
following each step exactly, while the local project works fine, also in production mode,
The deployment process starts off with npm errors Do you have any idea how this should be handled? tried npm cache clean, and deploying again.
Thanks!

`remote: glob error { Error: ENOTSUP: operation not supported on socket, scandir 'D:\home\site\wwwroot\node_modules\phantomjs-prebuilt\node_modules\request\node_modules\http-signature\node_modules\sshpk\man\man1\sshpk-sign.1'
remote:     at Error (native)
remote:   errno: -4049,
remote:   code: 'ENOTSUP',
remote:   syscall: 'scandir',
remote:   path: 'D:\\home\\site\\wwwroot\\node_modules\\phantomjs-prebuilt\\node_modules\\request\\node_modules\\http-signature\\node_modules\\sshpk\\man\\man1\\sshpk-sign.1' }
remote: glob error { Error: ENOTSUP: operation not supported on socket, scandir 'D:\home\site\wwwroot\node_modules\phantomjs-prebuilt\node_modules\request\node_modules\http-signature\node_modules\sshpk\man\man1\sshpk-conv.1'
remote:     at Error (native)
remote:   errno: -4049,
remote:   code: 'ENOTSUP',
remote:   syscall: 'scandir',
remote:   path: 'D:\\home\\site\\wwwroot\\node_modules\\phantomjs-prebuilt\\node_modules\\request\\node_modules\\http-signature\\node_modules\\sshpk\\man\\man1\\sshpk-conv.1' }
remote: glob error { Error: ENOTSUP: operation not supported on socket, scandir 'D:\home\site\wwwroot\node_modules\phantomjs-prebuilt\node_modules\request\node_modules\http-signature\node_modules\sshpk\man\man1\sshpk-verify.1'
remote:     at Error (native)
remote:   errno: -4049,
remote:   code: 'ENOTSUP',
remote:   syscall: 'scandir',
remote:   path: 'D:\\home\\site\\wwwroot\\node_modules\\phantomjs-prebuilt\\node_modules\\request\\node_modules\\http-signature\\node_modules\\sshpk\\man\\man1\\sshpk-verify.1' }
remote: glob error { Error: ENOTSUP: operation not supported on socket, scandir 'D:\home\site\wwwroot\node_modules\phantomjs-prebuilt\node_modules\request\node_modules\http-signature\node_modules\sshpk\bin\sshpk-conv'
remote:     at Error (native)
remote:   errno: -4049,
remote:   code: 'ENOTSUP',
remote:   syscall: 'scandir',
remote:   path: 'D:\\home\\site\\wwwroot\\node_modules\\phantomjs-prebuilt\\node_modules\\request\\node_modules\\http-signature\\node_modules\\sshpk\\bin\\sshpk-conv' }
remote: glob error { Error: ENOTSUP: operation not supported on socket, scandir 'D:\home\site\wwwroot\node_modules\phantomjs-prebuilt\node_modules\request\node_modules\http-signature\node_modules\sshpk\bin\sshpk-sign'
remote:     at Error (native)
remote:   errno: -4049,
remote:   code: 'ENOTSUP',
remote:   syscall: 'scandir',
remote:   path: 'D:\\home\\site\\wwwroot\\node_modules\\phantomjs-prebuilt\\node_modules\\request\\node_modules\\http-signature\\node_modules\\sshpk\\bin\\sshpk-sign' }
remote: glob error { Error: ENOTSUP: operation not supported on socket, scandir 'D:\home\site\wwwroot\node_modules\phantomjs-prebuilt\node_modules\request\node_modules\http-signature\node_modules\sshpk\bin\sshpk-verify'
remote:     at Error (native)
remote:   errno: -4049,
remote:   code: 'ENOTSUP',
remote:   syscall: 'scandir',
remote:   path: 'D:\\home\\site\\wwwroot\\node_modules\\phantomjs-prebuilt\\node_modules\\request\\node_modules\\http-signature\\node_modules\\sshpk\\bin\\sshpk-verify' }
=========================================================
... successful npm calls
=========================================================
emote: npm ERR! System Windows_NT 6.2.9200
remote: npm ERR! command "D:\\Program Files (x86)\\nodejs\\6.9.1\\node.exe" "D:\\Program Files (x86)\\npm\\1.4.9\\node_modules\\npm\\bin\\npm-cli.js" "install" "--production"
remote: npm ERR! cwd D:\home\site\wwwroot
remote: npm ERR! node -v v6.9.1
remote: npm ERR! npm -v 1.4.9
remote: npm ERR! path D:\home\site\wwwroot\node_modules\phantomjs-prebuilt\node_modules\request\node_modules\hawk\node_modules\cryptiles
remote: npm ERR! syscall mkdir
remote: npm ERR! fstream_path D:\home\site\wwwroot\node_modules\phantomjs-prebuilt\node_modules\request\node_modules\hawk\node_modules\cryptiles\LICENSE
remote: npm ERR! fstream_type File
remote: npm ERR! fstream_class FileWriter
remote: npm ERR! code EEXIST
remote: npm ERR! errno -4075
remote: npm ERR! fstream_stack D:\Program Files (x86)\npm\1.4.9\node_modules\npm\node_modules\fstream\lib\writer.js:171:23
remote: npm ERR! fstream_stack D:\Program Files (x86)\npm\1.4.9\node_modules\npm\node_modules\mkdirp\index.js:37:53
remote: npm ERR! fstream_stack FSReqWrap.oncomplete (fs.js:123:15)
remote: npm ERR! EEXIST: file already exists, mkdir 'D:\home\site\wwwroot\node_modules\phantomjs-prebuilt\node_modules\request\node_modules\hawk\node_modules\sntp'
remote: File exists: D:\home\site\wwwroot\node_modules\phantomjs-prebuilt\node_modules\request\node_modules\hawk\node_modules\snt
remote: Move it away, and try again. 
remote: 
remote: npm ERR! System Windows_NT 6.2.9200
remote: npm ERR! command "D:\\Program Files (x86)\\nodejs\\6.9.1\\node.exe" "D:\\Program Files (x86)\\npm\\1.4.9\\node_modules\\npm\\bin\\npm-cli.js" "install" "--production"
remote: npm ERR! cwd D:\home\site\wwwroot
remote: npm ERR! node -v v6.9.1
remote: npm ERR! npm -v 1.4.9
remote: npm ERR! path D:\home\site\wwwroot\node_modules\phantomjs-prebuilt\node_modules\request\node_modules\hawk\node_modules\sntp
remote: npm ERR! syscall mkdir
remote: npm ERR! fstream_path D:\home\site\wwwroot\node_modules\phantomjs-prebuilt\node_modules\request\node_modules\hawk\node_modules\sntp\LICENSE
remote: npm ERR! fstream_type File
remote: npm ERR! fstream_class FileWriter
remote: npm ERR! code EEXIST
remote: npm ERR! errno -4075
remote: npm ERR! fstream_stack D:\Program Files (x86)\npm\1.4.9\node_modules\npm\node_modules\fstream\lib\writer.js:171:23
remote: npm ERR! fstream_stack D:\Program Files (x86)\npm\1.4.9\node_modules\npm\node_modules\mkdirp\index.js:37:53
remote: npm ERR! fstream_stack FSReqWrap.oncomplete (fs.js:123:15)
remote: npm ERR! Error: ENOENT: no such file or directory, open 'D:\home\site\wwwroot\node_modules\phantomjs-prebuilt\node_modules\request\node_modules\hawk\node_modules\hoek\LICENSE'
remote: npm ERR!     at Error (native)
remote: npm ERR! If you need help, you may report this *entire* log,
remote: npm ERR! including the npm and node versions, at:
remote: npm ERR!     <http://github.com/npm/npm/issues>
remote: 
remote: npm ERR! System Windows_NT 6.2.9200
remote: npm ERR! command "D:\\Program Files (x86)\\nodejs\\6.9.1\\node.exe" "D:\\Program Files (x86)\\npm\\1.4.9\\node_modules\\npm\\bin\\npm-cli.js" "install" "--production"
remote: npm ERR! cwd D:\home\site\wwwroot
remote: npm ERR! node -v v6.9.1
remote: npm ERR! npm -v 1.4.9
remote: npm ERR! path D:\home\site\wwwroot\node_modules\phantomjs-prebuilt\node_modules\request\node_modules\hawk\node_modules\hoek\LICENSE
remote: npm ERR! syscall open
remote: npm ERR! code ENOENT
remote: npm ERR! errno -4058
remote: npm http GET https://registry.npmjs.org/require_optional
remote: npm http GET https://registry.npmjs.org/bson
remote: npm ERR! Error: EPERM: operation not permitted, chmod 'D:\home\site\wwwroot\node_modules\phantomjs-prebuilt\node_modules\request\node_modules\hawk\node_modules\boom\CONTRIBUTING.md'
remote: npm ERR!     at Error (native)
remote: npm ERR!  { Error: EPERM: operation not permitted, chmod 'D:\home\site\wwwroot\node_modules\phantomjs-prebuilt\node_modules\request\node_modules\hawk\node_modules\boom\CONTRIBUTING.md'
remote: npm ERR!     at Error (native)
remote: npm ERR!   errno: -4048,
remote: npm ERR!   code: 'EPERM',
remote: npm ERR!   syscall: 'chmod',
remote: npm ERR!   path: 'D:\\home\\site\\wwwroot\\node_modules\\phantomjs-prebuilt\\node_modules\\request\\node_modules\\hawk\\node_modules\\boom\\CONTRIBUTING.md',
remote: npm ERR!   fstream_finish_call: 'chmod',
remote: npm ERR!   fstream_type: 'File',
remote: npm ERR!   fstream_path: 'D:\\home\\site\\wwwroot\\node_modules\\phantomjs-prebuilt\\node_modules\\request\\node_modules\\hawk\\node_modules\\boom\\CONTRIBUTING.md',
remote: npm ERR!   fstream_class: 'FileWriter',
remote: npm ERR!   fstream_stack: 
remote: npm ERR!    [ 'D:\\Program Files (x86)\\npm\\1.4.9\\node_modules\\npm\\node_modules\\fstream\\lib\\writer.js:305:19',
remote: npm ERR!      'FSReqWrap.oncomplete (fs.js:123:15)' ] }
remote: npm ERR! 
remote: npm ERR! Please try running this command again as root/Administrator.
remote: 
remote: npm ERR! System Windows_NT 6.2.9200
remote: npm ERR! command "D:\\Program Files (x86)\\nodejs\\6.9.1\\node.exe" "D:\\Program Files (x86)\\npm\\1.4.9\\node_modules\\npm\\bin\\npm-cli.js" "install" "--production"
remote: npm ERR! cwd D:\home\site\wwwroot
remote: npm ERR! node -v v6.9.1
remote: npm ERR! npm -v 1.4.9
remote: npm ERR! path D:\home\site\wwwroot\node_modules\phantomjs-prebuilt\node_modules\request\node_modules\hawk\node_modules\boom\CONTRIBUTING.md
remote: npm ERR! syscall chmod
remote: npm ERR! fstream_path D:\home\site\wwwroot\node_modules\phantomjs-prebuilt\node_modules\request\node_modules\hawk\node_modules\boom\CONTRIBUTING.md
remote: npm ERR! fstream_type File
remote: npm ERR! fstream_class FileWriter
remote: npm ERR! fstream_finish_call chmod
remote: npm ERR! code EPERM
remote: npm ERR! errno -4048
remote: npm ERR! stack Error: EPERM: operation not permitted, chmod 'D:\home\site\wwwroot\node_modules\phantomjs-prebuilt\node_modules\request\node_modules\hawk\node_modules\boom\CONTRIBUTING.md'
remote: npm ERR! stack     at Error (native)
remote: npm ERR! fstream_stack D:\Program Files (x86)\npm\1.4.9\node_modules\npm\node_modules\fstream\lib\writer.js:305:19
remote: npm ERR! fstream_stack FSReqWrap.oncomplete (fs.js:123:15)

=========================================================
... successful npm calls
=========================================================
remote: npm ERR! Error: EPERM: operation not permitted, lstat 'D:\home\site\wwwroot\node_modules\node-inspector\node_modules\v8-profiler\node_modules\node-pre-gyp\node_modules\npmlog\node_modules\are-we-there-yet\node_modules\readable-stream\LICENSE'
remote: npm ERR!     at Error (native)
remote: npm ERR!  { Error: EPERM: operation not permitted, lstat 'D:\home\site\wwwroot\node_modules\node-inspector\node_modules\v8-profiler\node_modules\node-pre-gyp\node_modules\npmlog\node_modules\are-we-there-yet\node_modules\readable-stream\LICENSE'
remote: npm ERR!     at Error (native)
remote: npm ERR!   errno: -4048,
remote: npm ERR!   code: 'EPERM',
remote: npm ERR!   syscall: 'lstat',
remote: npm ERR!   path: 'D:\\home\\site\\wwwroot\\node_modules\\node-inspector\\node_modules\\v8-profiler\\node_modules\\node-pre-gyp\\node_modules\\npmlog\\node_modules\\are-we-there-yet\\node_modules\\readable-stream\\LICENSE',
remote: npm ERR!   fstream_type: 'File',
remote: npm ERR!   fstream_path: 'D:\\home\\site\\wwwroot\\node_modules\\node-inspector\\node_modules\\v8-profiler\\node_modules\\node-pre-gyp\\node_modules\\npmlog\\node_modules\\are-we-there-yet\\node_modules\\readable-stream\\LICENSE',
remote: npm ERR!   fstream_class: 'FileWriter',
remote: npm ERR!   fstream_stack: 
remote: npm ERR!    [ 'D:\\Program Files (x86)\\npm\\1.4.9\\node_modules\\npm\\node_modules\\fstream\\lib\\writer.js:284:26',
remote: npm ERR!      'FSReqWrap.oncomplete (fs.js:123:15)' ] }
remote: npm ERR! 
remote: npm ERR! Please try running this command again as root/Administrator.
remote: 
remote: npm ERR! System Windows_NT 6.2.9200
remote: npm ERR! command "D:\\Program Files (x86)\\nodejs\\6.9.1\\node.exe" "D:\\Program Files (x86)\\npm\\1.4.9\\node_modules\\npm\\bin\\npm-cli.js" "install" "--production"
remote: npm ERR! cwd D:\home\site\wwwroot
remote: npm ERR! node -v v6.9.1
remote: npm ERR! npm -v 1.4.9
remote: npm ERR! path D:\home\site\wwwroot\node_modules\node-inspector\node_modules\v8-profiler\node_modules\node-pre-gyp\node_modules\npmlog\node_modules\are-we-there-yet\node_modules\readable-stream\LICENSE
remote: npm ERR! syscall lstat
remote: npm ERR! fstream_path D:\home\site\wwwroot\node_modules\node-inspector\node_modules\v8-profiler\node_modules\node-pre-gyp\node_modules\npmlog\node_modules\are-we-there-yet\node_modules\readable-stream\LICENSE
remote: npm ERR! fstream_type File
remote: npm ERR! fstream_class FileWriter
remote: npm ERR! code EPERM
remote: npm ERR! errno -4048
remote: npm ERR! stack Error: EPERM: operation not permitted, lstat 'D:\home\site\wwwroot\node_modules\node-inspector\node_modules\v8-profiler\node_modules\node-pre-gyp\node_modules\npmlog\node_modules\are-we-there-yet\node_modules\readable-stream\LICENSE'
remote: npm ERR! stack     at Error (native)
remote: npm ERR! fstream_stack D:\Program Files (x86)\npm\1.4.9\node_modules\npm\node_modules\fstream\lib\writer.js:284:26
remote: npm ERR! fstream_stack FSReqWrap.oncomplete (fs.js:123:15)
remote: npm ERR! Error: ENOENT: no such file or directory, chmod 'D:\home\site\wwwroot\node_modules\node-inspector\node_modules\v8-profiler\node_modules\node-pre-gyp\node_modules\tar-pack\node_modules\readable-stream\node_modules\safe-buffer\README.md'
remote: npm ERR!     at Error (native)
remote: npm ERR! If you need help, you may report this *entire* log,
remote: npm ERR! including the npm and node versions, at:
remote: npm ERR!     <http://github.com/npm/npm/issues>
remote: 
remote: npm ERR! System Windows_NT 6.2.9200
remote: npm ERR! command "D:\\Program Files (x86)\\nodejs\\6.9.1\\node.exe" "D:\\Program Files (x86)\\npm\\1.4.9\\node_modules\\npm\\bin\\npm-cli.js" "install" "--production"
remote: npm ERR! cwd D:\home\site\wwwroot
remote: npm ERR! node -v v6.9.1
remote: npm ERR! npm -v 1.4.9
remote: npm ERR! path D:\home\site\wwwroot\node_modules\node-inspector\node_modules\v8-profiler\node_modules\node-pre-gyp\node_modules\tar-pack\node_modules\readable-stream\node_modules\safe-buffer\README.md
remote: npm ERR! syscall chmod
remote: npm ERR! fstream_path D:\home\site\wwwroot\node_modules\node-inspector\node_modules\v8-profiler\node_modules\node-pre-gyp\node_modules\tar-pack\node_modules\readable-stream\node_modules\safe-buffer\README.md
remote: npm ERR! fstream_type File
remote: npm ERR! fstream_class FileWriter
remote: npm ERR! fstream_finish_call chmod
remote: npm ERR! code ENOENT
remote: npm ERR! errno -4058
remote: npm ERR! fstream_stack D:\Program Files (x86)\npm\1.4.9\node_modules\npm\node_modules\fstream\lib\writer.js:305:19
remote: npm ERR! fstream_stack FSReqWrap.oncomplete (fs.js:123:15)
remote: npm ERR! EEXIST: file already exists, mkdir 'D:\home\site\wwwroot\node_modules\node-inspector\node_modules\v8-profiler\node_modules\node-pre-gyp\node_modules\tar-pack\node_modules\fstream\node_modules\inherits'
remote: File exists: D:\home\site\wwwroot\node_modules\node-inspector\node_modules\v8-profiler\node_modules\node-pre-gyp\node_modules\tar-pack\node_modules\fstream\node_modules\inherits
remote: Move it away, and try again. 
remote: 
remote: npm ERR! System Windows_NT 6.2.9200
remote: npm ERR! command "D:\\Program Files (x86)\\nodejs\\6.9.1\\node.exe" "D:\\Program Files (x86)\\npm\\1.4.9\\node_modules\\npm\\bin\\npm-cli.js" "install" "--production"
remote: npm ERR! cwd D:\home\site\wwwroot
remote: npm ERR! node -v v6.9.1
remote: npm ERR! npm -v 1.4.9
remote: npm ERR! path D:\home\site\wwwroot\node_modules\node-inspector\node_modules\v8-profiler\node_modules\node-pre-gyp\node_modules\tar-pack\node_modules\fstream\node_modules\inherits
remote: npm ERR! syscall mkdir
remote: npm ERR! fstream_path D:\home\site\wwwroot\node_modules\node-inspector\node_modules\v8-profiler\node_modules\node-pre-gyp\node_modules\tar-pack\node_modules\fstream\node_modules\inherits\inherits.js
remote: npm ERR! fstream_type File
remote: npm ERR! fstream_class FileWriter
remote: npm ERR! code EEXIST
remote: npm ERR! errno -4075
remote: npm ERR! fstream_stack D:\Program Files (x86)\npm\1.4.9\node_modules\npm\node_modules\fstream\lib\writer.js:171:23
remote: npm ERR! fstream_stack D:\Program Files (x86)\npm\1.4.9\node_modules\npm\node_modules\mkdirp\index.js:37:53
remote: npm ERR! fstream_stack FSReqWrap.oncomplete (fs.js:123:15)
remote: npm ERR! Error: ENOENT: no such file or directory, open 'D:\home\site\wwwroot\node_modules\node-inspector\node_modules\v8-profiler\node_modules\node-pre-gyp\node_modules\tar-pack\node_modules\readable-stream\node_modules\process-nextick-args\test.js'
remote: npm ERR!     at Error (native)
remote: npm ERR! If you need help, you may report this *entire* log,
remote: npm ERR! including the npm and node versions, at:
remote: npm ERR!     <http://github.com/npm/npm/issues>
remote: 
remote: npm ERR! System Windows_NT 6.2.9200
remote: npm ERR! command "D:\\Program Files (x86)\\nodejs\\6.9.1\\node.exe" "D:\\Program Files (x86)\\npm\\1.4.9\\node_modules\\npm\\bin\\npm-cli.js" "install" "--production"
remote: npm ERR! cwd D:\home\site\wwwroot
remote: npm ERR! node -v v6.9.1
remote: npm ERR! npm -v 1.4.9
remote: npm ERR! path D:\home\site\wwwroot\node_modules\node-inspector\node_modules\v8-profiler\node_modules\node-pre-gyp\node_modules\tar-pack\node_modules\readable-stream\node_modules\process-nextick-args\test.js
remote: npm ERR! syscall open
remote: npm ERR! code ENOENT
remote: npm ERR! errno -4058
remote: npm ERR! Error: ENOENT: no such file or directory, open 'D:\home\site\wwwroot\node_modules\node-inspector\node_modules\v8-profiler\node_modules\node-pre-gyp\node_modules\tar\node_modules\fstream\examples\reader.js'
remote: npm ERR!     at Error (native)
remote: npm ERR! If you need help, you may report this *entire* log,
remote: npm ERR! including the npm and node versions, at:
remote: npm ERR!     <http://github.com/npm/npm/issues>
remote: 
remote: npm ERR! System Windows_NT 6.2.9200
remote: npm ERR! command "D:\\Program Files (x86)\\nodejs\\6.9.1\\node.exe" "D:\\Program Files (x86)\\npm\\1.4.9\\node_modules\\npm\\bin\\npm-cli.js" "install" "--production"
remote: npm ERR! cwd D:\home\site\wwwroot
remote: npm ERR! node -v v6.9.1
remote: npm ERR! npm -v 1.4.9
remote: npm ERR! path D:\home\site\wwwroot\node_modules\node-inspector\node_modules\v8-profiler\node_modules\node-pre-gyp\node_modules\tar\node_modules\fstream\examples\reader.js
remote: npm ERR! syscall open
remote: npm ERR! code ENOENT
remote: npm ERR! errno -4058
remote: npm ERR! Error: EPERM: operation not permitted, chmod 'D:\home\site\wwwroot\node_modules\node-inspector\node_modules\v8-profiler\node_modules\node-pre-gyp\node_modules\tar-pack\node_modules\readable-stream\node_modules\core-util-is\test.js'
remote: npm ERR!     at Error (native)
remote: npm ERR!  { Error: EPERM: operation not permitted, chmod 'D:\home\site\wwwroot\node_modules\node-inspector\node_modules\v8-profiler\node_modules\node-pre-gyp\node_modules\tar-pack\node_modules\readable-stream\node_modules\core-util-is\test.js'
remote: npm ERR!     at Error (native)
remote: npm ERR!   errno: -4048,
remote: npm ERR!   code: 'EPERM',
remote: npm ERR!   syscall: 'chmod',
remote: npm ERR!   path: 'D:\\home\\site\\wwwroot\\node_modules\\node-inspector\\node_modules\\v8-profiler\\node_modules\\node-pre-gyp\\node_modules\\tar-pack\\node_modules\\readable-stream\\node_modules\\core-util-is\\test.js',
remote: npm ERR!   fstream_finish_call: 'chmod',
remote: npm ERR!   fstream_type: 'File',
remote: npm ERR!   fstream_path: 'D:\\home\\site\\wwwroot\\node_modules\\node-inspector\\node_modules\\v8-profiler\\node_modules\\node-pre-gyp\\node_modules\\tar-pack\\node_modules\\readable-stream\\node_modules\\core-util-is\\test.js',
remote: npm ERR!   fstream_class: 'FileWriter',
remote: npm ERR!   fstream_stack: 
remote: npm ERR!    [ 'D:\\Program Files (x86)\\npm\\1.4.9\\node_modules\\npm\\node_modules\\fstream\\lib\\writer.js:305:19',
remote: npm ERR!      'FSReqWrap.oncomplete (fs.js:123:15)' ] }
remote: npm ERR! 
remote: npm ERR! Please try running this command again as root/Administrator.
remote: 
remote: npm ERR! System Windows_NT 6.2.9200
remote: npm ERR! command "D:\\Program Files (x86)\\nodejs\\6.9.1\\node.exe" "D:\\Program Files (x86)\\npm\\1.4.9\\node_modules\\npm\\bin\\npm-cli.js" "install" "--production"
remote: npm ERR! cwd D:\home\site\wwwroot
remote: npm ERR! node -v v6.9.1
remote: npm ERR! npm -v 1.4.9
remote: npm ERR! path D:\home\site\wwwroot\node_modules\node-inspector\node_modules\v8-profiler\node_modules\node-pre-gyp\node_modules\tar-pack\node_modules\readable-stream\node_modules\core-util-is\test.js
remote: npm ERR! syscall chmod
remote: npm ERR! fstream_path D:\home\site\wwwroot\node_modules\node-inspector\node_modules\v8-profiler\node_modules\node-pre-gyp\node_modules\tar-pack\node_modules\readable-stream\node_modules\core-util-is\test.js
remote: npm ERR! fstream_type File
remote: npm ERR! fstream_class FileWriter
remote: npm ERR! fstream_finish_call chmod
remote: npm ERR! code EPERM
remote: npm ERR! errno -4048
remote: npm ERR! stack Error: EPERM: operation not permitted, chmod 'D:\home\site\wwwroot\node_modules\node-inspector\node_modules\v8-profiler\node_modules\node-pre-gyp\node_modules\tar-pack\node_modules\readable-stream\node_modules\core-util-is\test.js'
remote: npm ERR! stack     at Error (native)
remote: npm ERR! fstream_stack D:\Program Files (x86)\npm\1.4.9\node_modules\npm\node_modules\fstream\lib\writer.js:305:19
remote: npm ERR! fstream_stack FSReqWrap.oncomplete (fs.js:123:15)
remote: npm ERR! Error: ENOENT: no such file or directory, lstat 'D:\home\site\wwwroot\node_modules\node-inspector\node_modules\v8-profiler\node_modules\node-pre-gyp\node_modules\tar-pack\node_modules\fstream\node_modules\graceful-fs\legacy-streams.js'
remote: npm ERR!     at Error (native)
remote: npm ERR! If you need help, you may report this *entire* log,
remote: npm ERR! including the npm and node versions, at:
remote: npm ERR!     <http://github.com/npm/npm/issues>
remote: 
remote: npm ERR! System Windows_NT 6.2.9200
remote: npm ERR! command "D:\\Program Files (x86)\\nodejs\\6.9.1\\node.exe" "D:\\Program Files (x86)\\npm\\1.4.9\\node_modules\\npm\\bin\\npm-cli.js" "install" "--production"
remote: npm ERR! cwd D:\home\site\wwwroot
remote: npm ERR! node -v v6.9.1
remote: npm ERR! npm -v 1.4.9
remote: npm ERR! path D:\home\site\wwwroot\node_modules\node-inspector\node_modules\v8-profiler\node_modules\node-pre-gyp\node_modules\tar-pack\node_modules\fstream\node_modules\graceful-fs\legacy-streams.js
remote: npm ERR! syscall lstat
remote: npm ERR! fstream_path D:\home\site\wwwroot\node_modules\node-inspector\node_modules\v8-profiler\node_modules\node-pre-gyp\node_modules\tar-pack\node_modules\fstream\node_modules\graceful-fs\legacy-streams.js
remote: npm ERR! fstream_type File
remote: npm ERR! fstream_class FileWriter
remote: npm ERR! code ENOENT
remote: npm ERR! errno -4058
remote: npm ERR! fstream_stack D:\Program Files (x86)\npm\1.4.9\node_modules\npm\node_modules\fstream\lib\writer.js:284:26
remote: npm ERR! fstream_stack FSReqWrap.oncomplete (fs.js:123:15)
remote: npm ERR! Error: ENOENT: no such file or directory, lstat 'D:\home\site\wwwroot\node_modules\node-inspector\node_modules\v8-profiler\node_modules\node-pre-gyp\node_modules\tar-pack\node_modules\readable-stream\node_modules\string_decoder\LICENSE'
remote: npm ERR!     at Error (native)
remote: npm ERR! If you need help, you may report this *entire* log,
remote: npm ERR! including the npm and node versions, at:
remote: npm ERR!     <http://github.com/npm/npm/issues>
remote: 
remote: npm ERR! System Windows_NT 6.2.9200
remote: npm ERR! command "D:\\Program Files (x86)\\nodejs\\6.9.1\\node.exe" "D:\\Program Files (x86)\\npm\\1.4.9\\node_modules\\npm\\bin\\npm-cli.js" "install" "--production"
remote: npm ERR! cwd D:\home\site\wwwroot
remote: npm ERR! node -v v6.9.1
remote: npm ERR! npm -v 1.4.9
remote: npm ERR! path D:\home\site\wwwroot\node_modules\node-inspector\node_modules\v8-profiler\node_modules\node-pre-gyp\node_modules\tar-pack\node_modules\readable-stream\node_modules\string_decoder\LICENSE
remote: npm ERR! syscall lstat
remote: npm ERR! fstream_path D:\home\site\wwwroot\node_modules\node-inspector\node_modules\v8-profiler\node_modules\node-pre-gyp\node_modules\tar-pack\node_modules\readable-stream\node_modules\string_decoder\LICENSE
remote: npm ERR! fstream_type File
remote: npm ERR! fstream_class FileWriter
remote: npm ERR! code ENOENT
remote: npm ERR! errno -4058
remote: npm ERR! fstream_stack D:\Program Files (x86)\npm\1.4.9\node_modules\npm\node_modules\fstream\lib\writer.js:284:26
remote: npm ERR! fstream_stack FSReqWrap.oncomplete (fs.js:123:15)
remote: npm ERR! Error: ENOENT: no such file or directory, lstat 'D:\home\site\wwwroot\node_modules\node-inspector\node_modules\v8-profiler\node_modules\node-pre-gyp\node_modules\tar-pack\node_modules\readable-stream\node_modules\util-deprecate\browser.js'
remote: npm ERR!     at Error (native)
remote: npm ERR! If you need help, you may report this *entire* log,
remote: npm ERR! including the npm and node versions, at:
remote: npm ERR!     <http://github.com/npm/npm/issues>
remote: 
remote: npm ERR! System Windows_NT 6.2.9200
remote: npm ERR! command "D:\\Program Files (x86)\\nodejs\\6.9.1\\node.exe" "D:\\Program Files (x86)\\npm\\1.4.9\\node_modules\\npm\\bin\\npm-cli.js" "install" "--production"
remote: npm ERR! cwd D:\home\site\wwwroot
remote: npm ERR! node -v v6.9.1
remote: npm ERR! npm -v 1.4.9
remote: npm ERR! path D:\home\site\wwwroot\node_modules\node-inspector\node_modules\v8-profiler\node_modules\node-pre-gyp\node_modules\tar-pack\node_modules\readable-stream\node_modules\util-deprecate\browser.js
remote: npm ERR! syscall lstat
remote: npm ERR! fstream_path D:\home\site\wwwroot\node_modules\node-inspector\node_modules\v8-profiler\node_modules\node-pre-gyp\node_modules\tar-pack\node_modules\readable-stream\node_modules\util-deprecate\browser.js
remote: npm ERR! fstream_type File
remote: npm ERR! fstream_class FileWriter
remote: npm ERR! code ENOENT
remote: npm ERR! errno -4058
remote: npm ERR! fstream_stack D:\Program Files (x86)\npm\1.4.9\node_modules\npm\node_modules\fstream\lib\writer.js:284:26
remote: npm ERR! fstream_stack FSReqWrap.oncomplete (fs.js:123:15)
remote: npm ERR! error rolling back Error: EPERM: operation not permitted, rmdir 'D:\home\site\wwwroot\node_modules\node-inspector\node_modules\v8-profiler\node_modules\node-pre-gyp'
remote: npm ERR! error rolling back     at Error (native)
remote: npm ERR! error rolling back  node-pre-gyp@0.6.36 { Error: EPERM: operation not permitted, rmdir 'D:\home\site\wwwroot\node_modules\node-inspector\node_modules\v8-profiler\node_modules\node-pre-gyp'
remote: npm ERR! error rolling back     at Error (native)
remote: npm ERR! error rolling back   errno: -4048,
remote: npm ERR! error rolling back   code: 'EPERM',
remote: npm ERR! error rolling back   syscall: 'rmdir',
remote: npm ERR! error rolling back   path: 'D:\\home\\site\\wwwroot\\node_modules\\node-inspector\\node_modules\\v8-profiler\\node_modules\\node-pre-gyp' }
remote: npm ERR! error rolling back Error: EPERM: operation not permitted, rmdir 'D:\home\site\wwwroot\node_modules\node-inspector\node_modules\v8-profiler\node_modules'
remote: npm ERR! error rolling back     at Error (native)
remote: npm ERR! error rolling back  v8-profiler@5.6.5 { Error: EPERM: operation not permitted, rmdir 'D:\home\site\wwwroot\node_modules\node-inspector\node_modules\v8-profiler\node_modules'
remote: npm ERR! error rolling back     at Error (native)
remote: npm ERR! error rolling back   errno: -4048,
remote: npm ERR! error rolling back   code: 'EPERM',
remote: npm ERR! error rolling back   syscall: 'rmdir',
remote: npm ERR! error rolling back   path: 'D:\\home\\site\\wwwroot\\node_modules\\node-inspector\\node_modules\\v8-profiler\\node_modules' }
remote: npm WARN optional dep failed, continuing node-inspector@0.12.10
remote: ............
remote: npm http GET https://registry.npmjs.org/co
remote: npm http GET https://registry.npmjs.org/json-stable-stringify
remote: npm http 304 https://registry.npmjs.org/co
remote: npm http 304 https://registry.npmjs.org/json-stable-stringify
remote: npm http GET https://registry.npmjs.org/jsonify
remote: npm http 304 https://registry.npmjs.org/jsonify
fatal: The remote end hung up unexpectedly
error: error in sideband demultiplexer
`

**Comment by prashanthmadi** [comment]
have you tried redeploy ? Also which pricing tier are you on (basic/standard) ?

I Just did a test deployment on my azure webapp and haven't received any of these errors.

**Comment by idan666** [comment]
Yes,
I already ended my relationship with testing Azure products. returned to AWS, with a little less appealing DevOps work to do. at least it's working. thanks!

**Comment by prashanthmadi** [comment]
@idan666 sorry to hear that.. I would be happy to jump on a call and help you setup for this.
